apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-db-secret
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-resend-secret
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.resend.apiKey | b64enc | quote }}
